### ISSUE TITLE
cli parsing fails on newline

### ISSUE THREAD

**Issue by jandrieu** [iriscouch/couchjs#6]
typing ['reset'] into the CLI gets the following error:

```
["fatal","unknown_error","SyntaxError: Unexpected token '\n    at Object.parse (native)\n    at Loop (eval at <anonymous> (/node_modules/couchjs/cli.js:77:21), <anonymous>:1559:16)\n    at eval (eval at <anonymous> (node_modules/couchjs/cli.js:77:21), <anonymous>:1576:1)\n    at node_modules/couchjs/cli.js:80:24"]
```

I'm not sure if couch's main is expected to clean up the \n or if the CLI should...  seems like the main.js api actually requires the \n, but it certainly isn't working.

**Comment by abdulbarik** [comment]
@jandrieu Did you resolved this issue? I am also getting the same things.
I am using it with node@0.8.28

**Comment by jandrieu** [comment]
@abdulbarik Unfortunately, I don't recall. We did get couch working, but not sure how we got past this particular item.
